name: Build ModOrganizer 2

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Build ModOrganizer 2
        uses: ModOrganizer2/build-with-mob-action@master
        with:
          qt-modules: qtpositioning qtwebchannel qtwebengine qtwebsockets
          mo2-third-parties:
            7z zlib fmt gtest libbsarch libloot openssl libffi bzip2 python lz4 spdlog
            boost boost-di sip pyqt pybind11 ss licenses explorerpp usvfs
          mo2-dependencies: cmake_common uibase githubpp bsatk esptk archive lootcli game_gamebryo

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: D:/a/modorganizer/modorganizer/build/modorganizer_super/modorganizer
          if-no-files-found: warn
          retention-days: 0
          compression-level: 6
